apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
  namespace: guestbook-dev
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-app
        image: k8s.gcr.io/echoserver:1.4 # Hoặc một image đơn giản khác
        ports:
        - containerPort: 8080
