apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-app
        image: k8s.gcr.io/echoserver:1.4 # Hoặc một image đơn giản khác
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer # Hoặc NodePort nếu không có LoadBalancer