apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guestbook
    tier: front
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: guestbook
        tier: front
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        ports:
        - name: http
          containerPort: 8080
        name: guestbook
        imagePullPolicy: Always
        resources: 
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits: 
            cpu: "250m"
            memory: "128Mi"
