apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: guestbook-dev
spec:
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort # Hoặc NodePort nếu không có LoadBalancer