apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 2
  name: guestbook
namespace: gb-dev
commonAnnotations:
  supported-by: nambgit@gmail.com
labels:
- includeSelectors: false
  pairs:
    project: guestbook
patches:
- path: service.yaml